version: '3.7'

services:
  app:
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    ports:
      - 9001:9001
    restart: always
    networks:
      - microsservices
networks:
  microsservices:
    external: true

      
              

           